"""status table

Revision ID: 1ab4fa84ef9b
Revises: 5834655c9a5c
Create Date: 2023-03-16 02:01:25.711550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab4fa84ef9b'
down_revision = '5834655c9a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('avaliable', sa.Boolean(), nullable=True),
    sa.Column('date_of_hire', sa.Date(), nullable=True),
    sa.Column('end_of_handover', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    # ### end Alembic commands ###
