"""status table

Revision ID: 7037e013b814
Revises: 4e965cd181c3
Create Date: 2023-03-17 11:03:21.262648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7037e013b814'
down_revision = '4e965cd181c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('avaliable', sa.Boolean(), nullable=True),
    sa.Column('date_of_hire', sa.Date(), nullable=True),
    sa.Column('date_of_handover', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    # ### end Alembic commands ###
